name: paye
description: A Dart package for calculating PAYE (Pay As You Earn) tax and pension contributions.
version: 1.0.4
repository: https://github.com/gilbert-amo/flutter_paye

environment:
  sdk: ^3.6.2

# Add regular dependencies here.
dependencies:
  decimal: ^3.2.1
  # path: ^1.8.0
  args: ^2.4.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
